// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/form": {
    params: {};
  };
  "/drag": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/form" | "/drag";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/form.tsx": {
    id: "routes/form";
    page: "/form";
  };
  "routes/drag.tsx": {
    id: "routes/drag";
    page: "/drag";
  };
};